services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    env_file:
      - ../apps/web/.env
    volumes:
      - ../apps/web:/var/www/html
      - ./apps/web/docker/.apache-vhost-govdo.conf:/opt/docker/etc/httpd/vhost.common.d/govdo.conf
    ports:
      - "${APP_PORT:-80}:80"
      - "${APP_PORT_SSL:-443}:443"
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_DEBUGGER=xdebug
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_START_WITH_REQUEST=trigger
      - XDEBUG_TRIGGER_VALUE=PHPSTORM
      - php.xdebug.log=/var/www/html/storage/logs/xdebug.log
    networks:
      - custom_network

  db:
    extends:
      file: docker-compose.db.yml
      service: db

  redis:
    image: redis:7.4
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD:-redispassword}" ]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - custom_network

volumes:
  govdo_mysqldata:
    external: true

networks:
  custom_network:
    name: "govdo_shared_network"
    external: true