services:
  db:
    image: mariadb:10.11
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=basicpassword
    volumes:
      - govdo_mysqldata:/var/lib/mysql
    networks:
      custom_network:
        aliases:
          - shared-db

volumes:
  govdo_mysqldata:
    external: true

networks:
  custom_network:
    name: "govdo_shared_network"
    external: true