services:
  app:
    image: webdevops/php-apache-dev:8.3
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
      - "${APP_PORT:-80}:80"
      - "${APP_PORT_SSL:-443}:443"
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_DEBUGGER=xdebug
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_START_WITH_REQUEST=trigger
      - XDEBUG_TRIGGER_VALUE=PHPSTORM
      - php.xdebug.log=/var/www/html/storage/logs/xdebug.log
      - VHOST_NAME="${VHOST_NAME:-worktree}"
    networks:
      - custom_network
  redis:
    image: redis:7.4
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD:-redispassword}" ]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - custom_network

networks:
  custom_network:
    name: "govdo_shared_network"
    external: true